#!/usr/bin/env python

import sys
import random
import struct

BLOCKSIZE = 16 #AES block size in bytes

def main(N):
	"""Generate N blocks of random data for AES."""
	n_bytes = N*BLOCKSIZE
	s_long  = struct.calcsize('Q')
	n_longs = n_bytes / s_long

	for i in range(n_longs):
		bits = random.getrandbits(s_long*8)
		sys.stdout.write(struct.pack('Q', bits))

if __name__ == '__main__':
	try:
		main(int(sys.argv[1]))
	except:
		main(512)
