#!/usr/bin/env python

import sys
from subprocess import Popen, PIPE

def main(impl, file):
	tested = passed = 0

	f = open(file)
	for line in f:
		if line.startswith('KEY='):
			key = line[4:].strip()
		elif line.startswith('PT='):
			pt = line[3:].strip()
		elif line.startswith('CT='):
			ct = line[3:].strip()
			tested += 1
			result = aes(impl, key, pt)
			if result == ct:
				passed += 1
	f.close()

	print("%d/%d TESTS PASSED" % (passed, tested))

def aes(impl, key, pt):
	return Popen([impl, key, pt], stdout=PIPE).communicate()[0].strip()

if __name__ == '__main__':
	main(sys.argv[1], sys.argv[2])
